version: "3.3" 

services:
  db:
    image: mysql
    container_name: my_redis
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_PASSWORD=pass
      - MYSQL_USER=redis
  
  redis:
    image: redis
    command: redis-server --requirepass pass
    ports: 
      -  "6379:6379"